# Generated by Django 3.1.6 on 2021-02-17 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1611), django.core.validators.MaxLengthValidator(2021)]),
        ),
    ]
