# Generated by Django 3.1.6 on 2021-02-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_companies', '0003_auto_20210217_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
